[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "nuft"
authors = [{name = "nuft", email = "nuft@u.northwestern.edu"}]
dynamic = ["version", "description"]